#  find the correlation of the dataset ( in descending order)

In [2]:
import numpy as np
import pandas as pd

In [3]:
data={'age':[1,2,3,4,5],
     'income':[100,200,300,600,800],
     'loan_approved':[0,0,0,1,1]}

In [4]:
data=pd.DataFrame(data)

In [5]:
data

age  income  loan_approved
0    1     100              0
1    2     200              0
2    3     300              0
3    4     600              1
4    5     800              1

In [6]:
correlation=data.corr()['loan_approved'] # give only 1 feature that is depend feature to find which feature is more depend

In [7]:
correlation

age              0.866025
income           0.939336
loan_approved    1.000000
Name: loan_approved, dtype: float64

In [8]:
sorted_correlation=correlation.sort_values(ascending=False)
sorted_correation

NameError: name 'sorted_correation' is not defined

# using the iris dataset to find the best 2 feature

In [9]:
import pandas as pd
from sklearn.datasets import load_iris

In [10]:
data=load_iris()

In [11]:
from sklearn.feature_selection import SelectKBest,f_classif

In [12]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [13]:
dir(data)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [14]:
x,y=data.data,data.target

In [15]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [17]:
df=pd.DataFrame(data.data,columns=data.feature_names)

In [18]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [19]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [20]:
df['target']=data.target

In [21]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [22]:
k_best=SelectKBest(score_func=f_classif,k=2)

In [23]:
k_best.fit_transform(x,y)

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.4, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [24]:
select_indices=k_best.get_support(indices=True)

In [208]:
select_features=df.columns[select_indices]

In [209]:
select_features

Index(['petal length (cm)', 'petal width (cm)'], dtype='object')

# find the best 1 feature in the random dataset

In [210]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest,f_classif

In [211]:
data={'age':[1,2,3,4,5],
     'income':[100,200,300,600,800],
     'loan_approved':[0,0,0,1,1]}

In [212]:
data=pd.DataFrame(data)

In [213]:
data

age  income  loan_approved
0    1     100              0
1    2     200              0
2    3     300              0
3    4     600              1
4    5     800              1

In [214]:
x=data[['age','income']]
y=data['loan_approved']

In [215]:
x

age  income
0    1     100
1    2     200
2    3     300
3    4     600
4    5     800

In [216]:
y

0    0
1    0
2    0
3    1
4    1
Name: loan_approved, dtype: int64

In [217]:
x=np.array(x)

In [218]:
x

array([[  1, 100],
       [  2, 200],
       [  3, 300],
       [  4, 600],
       [  5, 800]], dtype=int64)

In [219]:
k_best=SelectKBest(score_func=f_classif,k=1)

In [220]:
k_best=k_best.fit(x,y)

In [221]:
k_best

SelectKBest(k=1)

In [222]:
select_indices=k_best.get_support(indices=True)
select_indices

array([1], dtype=int64)

In [223]:
selected_feature=data.columns[select_indices]
selected_feature

Index(['income'], dtype='object')

# FINDING THE CORRELATION OF THE GIVEN DATASET (all realtion of the dataset  given multiple columns)

In [224]:
correlation=data.corr()
correlation

age    income  loan_approved
age            1.000000  0.976187       0.866025
income         0.976187  1.000000       0.939336
loan_approved  0.866025  0.939336       1.000000

In [225]:
sorted_correlation = correlation.unstack().sort_values(ascending=False)
sorted_correlation


age            age              1.000000
income         income           1.000000
loan_approved  loan_approved    1.000000
age            income           0.976187
income         age              0.976187
               loan_approved    0.939336
loan_approved  income           0.939336
age            loan_approved    0.866025
loan_approved  age              0.866025
dtype: float64

# find the correlation ( using the target value only) using only one feature 

In [226]:
correlation=data.corr()['loan_approved']
correlation

age              0.866025
income           0.939336
loan_approved    1.000000
Name: loan_approved, dtype: float64

In [227]:
correlation=correlation.abs()

In [228]:
sorted_correlation = correlation.sort_values(ascending=False)
sorted_correlation

loan_approved    1.000000
income           0.939336
age              0.866025
Name: loan_approved, dtype: float64

# just predict the given feature using the linear regression

In [384]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [385]:
data

age  income  loan_approved
0    1     100              0
1    2     200              0
2    3     300              0
3    4     600              1
4    5     800              1

In [414]:
x=data[['income']]
y=data['loan_approved']

In [415]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [416]:
model=LinearRegression()

In [417]:
model.fit(x_train,y_train)

LinearRegression()

In [436]:
model.score(x_test,y_test)

0.7950138504155121

In [440]:
pred = model.predict([[199]])

print("Prediction:", pred)

if pred[0] == 1 or pred[0] > 1:
    print('Yes')
elif pred[0] == 0 or pred[0] < 0:
    print('No')
else:
    print("Unknown prediction:", pred[0])

    
        

Prediction: [0.05052632]
Unknown prediction: 0.05052631578947364


# wrapper method to select the  best feature

In [292]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import RFE  #recursive feature elimination
from sklearn.linear_model import LogisticRegression

In [293]:
model = LogisticRegression()

In [294]:
rfe = RFE(model, n_features_to_select=2)

In [295]:
rfe.fit(X, y)

C:\Users\Nitheesh\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


RFE(estimator=LogisticRegression(), n_features_to_select=2)

In [296]:
selected_features = X[:, rfe.support_]

In [297]:
print("Selected feature indices:", rfe.support_)

Selected feature indices: [False False  True  True]


In [299]:
selected_feature_indices = rfe.support_

In [303]:
selected_feature_names = [f'Feature {i+1}' for i in range(X.shape[1]) if rfe.support_[i]]


In [304]:
print("Selected feature names:", selected_feature_names)

Selected feature names: ['Feature 3', 'Feature 4']


In [306]:
selected_feature_names = [feature_name for i, feature_name in enumerate(iris.feature_names) if selected_feature_indices[i]]

In [307]:
print("Selected feature names:", selected_feature_names)

Selected feature names: ['petal length (cm)', 'petal width (cm)']


# easy way to find the good feature of the dataset

In [359]:
import pandas as pd
from sklearn.feature_selection import SelectKBest
from sklearn.datasets import load_iris

In [360]:
df=load_iris()

In [361]:
dir(df)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [362]:
y=df.target

In [363]:
x=df.data

In [364]:
df=pd.DataFrame(df.data,columns=df.feature_names)

In [365]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [366]:
df['target']=y

In [367]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [368]:
k_best=SelectKBest(score_func=f_classif,k=3)

In [369]:
new=k_best.fit_transform(x,y)

In [370]:
selected_indices=k_best.get_support(indices=True)

In [372]:
select_feature=df.columns[selected_indices]
select_feature

Index(['sepal length (cm)', 'petal length (cm)', 'petal width (cm)'], dtype='object')

In [373]:
corre=df.corr()['target']

In [374]:
corre

sepal length (cm)    0.782561
sepal width (cm)    -0.426658
petal length (cm)    0.949035
petal width (cm)     0.956547
target               1.000000
Name: target, dtype: float64

In [377]:
sorted_corre=corre.sort_values(ascending=False)
sorted_corre

target               1.000000
petal width (cm)     0.956547
petal length (cm)    0.949035
sepal length (cm)    0.782561
sepal width (cm)    -0.426658
Name: target, dtype: float64

# feature embeded (label encoding)

In [441]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [442]:
data={
    'item':['shirt','jeans','Dress','T-shirt','skirt'],
    'color':['blue','black','red','white','yellow'],
    'size':['medium','large','small','medium','large']
}

In [444]:
data=pd.DataFrame(data)

In [445]:
data

item   color    size
0    shirt    blue  medium
1    jeans   black   large
2    Dress     red   small
3  T-shirt   white  medium
4    skirt  yellow   large

In [447]:
data['size']

0    medium
1     large
2     small
3    medium
4     large
Name: size, dtype: object

In [448]:
label=LabelEncoder()

In [451]:
data['encoded_size']=label.fit_transform(data['size'])

In [452]:
data

item   color    size  encoded_size
0    shirt    blue  medium             1
1    jeans   black   large             0
2    Dress     red   small             2
3  T-shirt   white  medium             1
4    skirt  yellow   large             0

# feature embeded (OneHotEncoding)

In [455]:
from sklearn.preprocessing import OneHotEncoder

In [456]:
data={
    'fruit':['apple','banana','orange','grape','lemon'],
    'color':['red','yellow','orange','purple','yello']
}

In [457]:
data

{'fruit': ['apple', 'banana', 'orange', 'grape', 'lemon'],
 'color': ['red', 'yellow', 'orange', 'purple', 'yello']}

In [458]:
df=pd.DataFrame(data)

In [459]:
df

fruit   color
0   apple     red
1  banana  yellow
2  orange  orange
3   grape  purple
4   lemon   yello

In [460]:
encoded=OneHotEncoder()

In [465]:
onehotencoder=encoded.fit_transform(df[['color']]).toarray()

In [466]:
onehotencoder

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [471]:
encoded_df=pd.DataFrame(onehotencoder,columns=encoded.get_feature_names(['colors']))

In [472]:
df_encoded=pd.concat([df,encoded_df],axis=1)

In [475]:
df_encoded

fruit   color  colors_orange  colors_purple  colors_red  colors_yello  \
0   apple     red            0.0            0.0         1.0           0.0   
1  banana  yellow            0.0            0.0         0.0           0.0   
2  orange  orange            1.0            0.0         0.0           0.0   
3   grape  purple            0.0            1.0         0.0           0.0   
4   lemon   yello            0.0            0.0         0.0           1.0   

   colors_yellow  
0            0.0  
1            1.0  
2            0.0  
3            0.0  
4            0.0

# bianary encoding using the binary data

In [486]:
import pandas as pd
from category_encoders import BinaryEncoder

In [488]:
data={
    'device':['laptop','tv','smartphone','microvawe','tablet'],
    'portable':['yes','no','yes','no','yes']
}

In [489]:
df=pd.DataFrame(data)

In [490]:
df

device portable
0      laptop      yes
1          tv       no
2  smartphone      yes
3   microvawe       no
4      tablet      yes

In [494]:
encoder=BinaryEncoder(cols=['portable'])

In [495]:
encoder.fit_transform(df)

device  portable_0  portable_1
0      laptop           0           1
1          tv           1           0
2  smartphone           0           1
3   microvawe           1           0
4      tablet           0           1